# Generated by Django 4.1.2 on 2023-04-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalApp', '0002_wpay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpay',
            name='user',
        ),
        migrations.AddField(
            model_name='wpay',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
