# Generated by Django 4.1.2 on 2023-04-04 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalApp', '0003_remove_wpay_user_wpay_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wpay',
            old_name='paid',
            new_name='paide',
        ),
    ]
