# Generated by Django 4.0.5 on 2023-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalApp', '0004_rename_paid_wpay_paide'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
