# Generated by Django 4.0.5 on 2023-04-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalApp', '0005_worker_auth_token_worker_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_dt',
        ),
    ]
